name: GitHub Metrics

on:
  # Schedule updates (daily at midnight UTC)
  schedule:
    - cron: "0 0 * * *"

  # Allow manual triggering of the workflow
  workflow_dispatch:

  # Trigger the workflow on pushes to the main branch
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: production

    # Define minimal required permissions for security
    permissions:
      contents: write
      issues: read
      pull-requests: read
      # Add other permissions if required by specific plugins

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Fetch only the latest commit for faster performance

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest  # Updated to the correct version
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: vem882
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: true
          base_indepth: true
          config_octicon: true
          config_timezone: Europe/Helsinki
          config_twemoji: true
          plugin_languages: true
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_indepth: true
          plugin_languages_limit: 8
          plugin_languages_other: true
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 30
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
